export const ROLES = {
	ADMIN: "admin",
	BUYER: "buyer",
	SELLER: "seller",
	GUEST: "guest",
};

export const PERMISSIONS = {
	VIEW_PROFILE: "view_profile",
	VIEW_DASHBOARD: "view_dashboard",
	VIEW_PRODUCTS: "view_products",
	EDIT_PRODUCTS: "edit_products",
	DELETE_PRODUCTS: "delete_products",
};

export const ROLES_PERMISSIONS: Record<string, string[]> = {
	[ROLES.ADMIN]: [
		PERMISSIONS.VIEW_DASHBOARD,
		PERMISSIONS.VIEW_PRODUCTS,
		PERMISSIONS.DELETE_PRODUCTS,
	],
	[ROLES.BUYER]: [PERMISSIONS.VIEW_DASHBOARD, PERMISSIONS.VIEW_PRODUCTS],
	[ROLES.SELLER]: [PERMISSIONS.VIEW_DASHBOARD, PERMISSIONS.VIEW_PRODUCTS],
	[ROLES.GUEST]: [PERMISSIONS.VIEW_DASHBOARD],
};
