/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './router/__root'
import { Route as guestGuestRouteImport } from './router/(guest)/_guest'
import { Route as guestErrorsRouteImport } from './router/(guest)/_errors'
import { Route as guestAuthRouteImport } from './router/(guest)/_auth'
import { Route as dashboardAdminRouteImport } from './router/(dashboard)/admin'
import { Route as privateProductIndexRouteImport } from './router/(private)/product/index'
import { Route as guestGuestIndexRouteImport } from './router/(guest)/_guest/index'
import { Route as privateProductProductIdRouteImport } from './router/(private)/product/$productId'
import { Route as guestErrors503RouteImport } from './router/(guest)/_errors/503'
import { Route as guestErrors500RouteImport } from './router/(guest)/_errors/500'
import { Route as guestErrors404RouteImport } from './router/(guest)/_errors/404'
import { Route as guestErrors403RouteImport } from './router/(guest)/_errors/403'
import { Route as guestErrors401RouteImport } from './router/(guest)/_errors/401'
import { Route as guestAuthRegisterRouteImport } from './router/(guest)/_auth/register'
import { Route as guestAuthLoginRouteImport } from './router/(guest)/_auth/login'
import { Route as dashboardAdminDashboardRouteImport } from './router/(dashboard)/admin/dashboard'
import { Route as privateUsersProfileUserIdRouteImport } from './router/(private)/users/profile/$userId'
import { Route as dashboardAdminUsersListIndexRouteImport } from './router/(dashboard)/admin/users/list/index'
import { Route as dashboardAdminUsersFormIndexRouteImport } from './router/(dashboard)/admin/users/_form/index'

const guestGuestRoute = guestGuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => guestRoute,
} as any)
const guestErrorsRoute = guestErrorsRouteImport.update({
  id: '/_errors',
  getParentRoute: () => guestRoute,
} as any)
const guestAuthRoute = guestAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => guestRoute,
} as any)
const dashboardAdminRoute = dashboardAdminRouteImport.update({
  id: '/(dashboard)/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const privateProductIndexRoute = privateProductIndexRouteImport.update({
  id: '/(private)/product/',
  path: '/product/',
  getParentRoute: () => rootRouteImport,
} as any)
const guestGuestIndexRoute = guestGuestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => guestGuestRoute,
} as any)
const privateProductProductIdRoute = privateProductProductIdRouteImport.update({
  id: '/(private)/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const guestErrors503Route = guestErrors503RouteImport.update({
  id: '/503',
  path: '/503',
  getParentRoute: () => guestErrorsRoute,
} as any)
const guestErrors500Route = guestErrors500RouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => guestErrorsRoute,
} as any)
const guestErrors404Route = guestErrors404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => guestErrorsRoute,
} as any)
const guestErrors403Route = guestErrors403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => guestErrorsRoute,
} as any)
const guestErrors401Route = guestErrors401RouteImport.update({
  id: '/401',
  path: '/401',
  getParentRoute: () => guestErrorsRoute,
} as any)
const guestAuthRegisterRoute = guestAuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => guestAuthRoute,
} as any)
const guestAuthLoginRoute = guestAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => guestAuthRoute,
} as any)
const dashboardAdminDashboardRoute = dashboardAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => dashboardAdminRoute,
} as any)
const privateUsersProfileUserIdRoute =
  privateUsersProfileUserIdRouteImport.update({
    id: '/(private)/users/profile/$userId',
    path: '/users/profile/$userId',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardAdminUsersListIndexRoute =
  dashboardAdminUsersListIndexRouteImport.update({
    id: '/users/list/',
    path: '/users/list/',
    getParentRoute: () => dashboardAdminRoute,
  } as any)
const dashboardAdminUsersFormIndexRoute =
  dashboardAdminUsersFormIndexRouteImport.update({
    id: '/users/_form/',
    path: '/users/',
    getParentRoute: () => dashboardAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof dashboardAdminRouteWithChildren
  '/admin/dashboard': typeof dashboardAdminDashboardRoute
  '/login': typeof guestAuthLoginRoute
  '/register': typeof guestAuthRegisterRoute
  '/401': typeof guestErrors401Route
  '/403': typeof guestErrors403Route
  '/404': typeof guestErrors404Route
  '/500': typeof guestErrors500Route
  '/503': typeof guestErrors503Route
  '/product/$productId': typeof privateProductProductIdRoute
  '/': typeof guestGuestIndexRoute
  '/product': typeof privateProductIndexRoute
  '/users/profile/$userId': typeof privateUsersProfileUserIdRoute
  '/admin/users': typeof dashboardAdminUsersFormIndexRoute
  '/admin/users/list': typeof dashboardAdminUsersListIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof dashboardAdminRouteWithChildren
  '/admin/dashboard': typeof dashboardAdminDashboardRoute
  '/login': typeof guestAuthLoginRoute
  '/register': typeof guestAuthRegisterRoute
  '/401': typeof guestErrors401Route
  '/403': typeof guestErrors403Route
  '/404': typeof guestErrors404Route
  '/500': typeof guestErrors500Route
  '/503': typeof guestErrors503Route
  '/product/$productId': typeof privateProductProductIdRoute
  '/': typeof guestGuestIndexRoute
  '/product': typeof privateProductIndexRoute
  '/users/profile/$userId': typeof privateUsersProfileUserIdRoute
  '/admin/users': typeof dashboardAdminUsersFormIndexRoute
  '/admin/users/list': typeof dashboardAdminUsersListIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(dashboard)/admin': typeof dashboardAdminRouteWithChildren
  '/(guest)/_auth': typeof guestAuthRouteWithChildren
  '/(guest)/_errors': typeof guestErrorsRouteWithChildren
  '/(guest)/_guest': typeof guestGuestRouteWithChildren
  '/(dashboard)/admin/dashboard': typeof dashboardAdminDashboardRoute
  '/(guest)/_auth/login': typeof guestAuthLoginRoute
  '/(guest)/_auth/register': typeof guestAuthRegisterRoute
  '/(guest)/_errors/401': typeof guestErrors401Route
  '/(guest)/_errors/403': typeof guestErrors403Route
  '/(guest)/_errors/404': typeof guestErrors404Route
  '/(guest)/_errors/500': typeof guestErrors500Route
  '/(guest)/_errors/503': typeof guestErrors503Route
  '/(private)/product/$productId': typeof privateProductProductIdRoute
  '/(guest)/_guest/': typeof guestGuestIndexRoute
  '/(private)/product/': typeof privateProductIndexRoute
  '/(private)/users/profile/$userId': typeof privateUsersProfileUserIdRoute
  '/(dashboard)/admin/users/_form/': typeof dashboardAdminUsersFormIndexRoute
  '/(dashboard)/admin/users/list/': typeof dashboardAdminUsersListIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/admin/dashboard'
    | '/login'
    | '/register'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/product/$productId'
    | '/'
    | '/product'
    | '/users/profile/$userId'
    | '/admin/users'
    | '/admin/users/list'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/admin/dashboard'
    | '/login'
    | '/register'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/product/$productId'
    | '/'
    | '/product'
    | '/users/profile/$userId'
    | '/admin/users'
    | '/admin/users/list'
  id:
    | '__root__'
    | '/(dashboard)/admin'
    | '/(guest)/_auth'
    | '/(guest)/_errors'
    | '/(guest)/_guest'
    | '/(dashboard)/admin/dashboard'
    | '/(guest)/_auth/login'
    | '/(guest)/_auth/register'
    | '/(guest)/_errors/401'
    | '/(guest)/_errors/403'
    | '/(guest)/_errors/404'
    | '/(guest)/_errors/500'
    | '/(guest)/_errors/503'
    | '/(private)/product/$productId'
    | '/(guest)/_guest/'
    | '/(private)/product/'
    | '/(private)/users/profile/$userId'
    | '/(dashboard)/admin/users/_form/'
    | '/(dashboard)/admin/users/list/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  dashboardAdminRoute: typeof dashboardAdminRouteWithChildren
  privateProductProductIdRoute: typeof privateProductProductIdRoute
  privateProductIndexRoute: typeof privateProductIndexRoute
  privateUsersProfileUserIdRoute: typeof privateUsersProfileUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(guest)/_guest': {
      id: '/(guest)/_guest'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof guestGuestRouteImport
      parentRoute: typeof guestRoute
    }
    '/(guest)/_errors': {
      id: '/(guest)/_errors'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof guestErrorsRouteImport
      parentRoute: typeof guestRoute
    }
    '/(guest)/_auth': {
      id: '/(guest)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof guestAuthRouteImport
      parentRoute: typeof guestRoute
    }
    '/(dashboard)/admin': {
      id: '/(dashboard)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof dashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/product/': {
      id: '/(private)/product/'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof privateProductIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(guest)/_guest/': {
      id: '/(guest)/_guest/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof guestGuestIndexRouteImport
      parentRoute: typeof guestGuestRoute
    }
    '/(private)/product/$productId': {
      id: '/(private)/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof privateProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(guest)/_errors/503': {
      id: '/(guest)/_errors/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof guestErrors503RouteImport
      parentRoute: typeof guestErrorsRoute
    }
    '/(guest)/_errors/500': {
      id: '/(guest)/_errors/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof guestErrors500RouteImport
      parentRoute: typeof guestErrorsRoute
    }
    '/(guest)/_errors/404': {
      id: '/(guest)/_errors/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof guestErrors404RouteImport
      parentRoute: typeof guestErrorsRoute
    }
    '/(guest)/_errors/403': {
      id: '/(guest)/_errors/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof guestErrors403RouteImport
      parentRoute: typeof guestErrorsRoute
    }
    '/(guest)/_errors/401': {
      id: '/(guest)/_errors/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof guestErrors401RouteImport
      parentRoute: typeof guestErrorsRoute
    }
    '/(guest)/_auth/register': {
      id: '/(guest)/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof guestAuthRegisterRouteImport
      parentRoute: typeof guestAuthRoute
    }
    '/(guest)/_auth/login': {
      id: '/(guest)/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof guestAuthLoginRouteImport
      parentRoute: typeof guestAuthRoute
    }
    '/(dashboard)/admin/dashboard': {
      id: '/(dashboard)/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof dashboardAdminDashboardRouteImport
      parentRoute: typeof dashboardAdminRoute
    }
    '/(private)/users/profile/$userId': {
      id: '/(private)/users/profile/$userId'
      path: '/users/profile/$userId'
      fullPath: '/users/profile/$userId'
      preLoaderRoute: typeof privateUsersProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/admin/users/list/': {
      id: '/(dashboard)/admin/users/list/'
      path: '/users/list'
      fullPath: '/admin/users/list'
      preLoaderRoute: typeof dashboardAdminUsersListIndexRouteImport
      parentRoute: typeof dashboardAdminRoute
    }
    '/(dashboard)/admin/users/_form/': {
      id: '/(dashboard)/admin/users/_form/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof dashboardAdminUsersFormIndexRouteImport
      parentRoute: typeof dashboardAdminRoute
    }
  }
}

interface dashboardAdminRouteChildren {
  dashboardAdminDashboardRoute: typeof dashboardAdminDashboardRoute
  dashboardAdminUsersFormIndexRoute: typeof dashboardAdminUsersFormIndexRoute
  dashboardAdminUsersListIndexRoute: typeof dashboardAdminUsersListIndexRoute
}

const dashboardAdminRouteChildren: dashboardAdminRouteChildren = {
  dashboardAdminDashboardRoute: dashboardAdminDashboardRoute,
  dashboardAdminUsersFormIndexRoute: dashboardAdminUsersFormIndexRoute,
  dashboardAdminUsersListIndexRoute: dashboardAdminUsersListIndexRoute,
}

const dashboardAdminRouteWithChildren = dashboardAdminRoute._addFileChildren(
  dashboardAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  dashboardAdminRoute: dashboardAdminRouteWithChildren,
  privateProductProductIdRoute: privateProductProductIdRoute,
  privateProductIndexRoute: privateProductIndexRoute,
  privateUsersProfileUserIdRoute: privateUsersProfileUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
